// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USPEducation.Data;

#nullable disable

namespace USPGradeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322082603_UpdateGradesWithActualStudentIds")]
    partial class UpdateGradesWithActualStudentIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("USPGradeSystem.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeLetter")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<float>("Marks")
                        .HasColumnType("real");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = "CS101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "S12345678"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = "CS102",
                            GradeLetter = "A+",
                            Marks = 92f,
                            StudentId = "S12345678"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = "MATH101",
                            GradeLetter = "B+",
                            Marks = 78f,
                            StudentId = "S12345678"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = "CS101",
                            GradeLetter = "C",
                            Marks = 65f,
                            StudentId = "S12345679"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = "CS102",
                            GradeLetter = "A",
                            Marks = 88f,
                            StudentId = "S12345679"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = "MATH101",
                            GradeLetter = "B",
                            Marks = 75f,
                            StudentId = "S12345679"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = "ACC101",
                            GradeLetter = "A+",
                            Marks = 90f,
                            StudentId = "S12345680"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = "FIN101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "S12345680"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = "MGT101",
                            GradeLetter = "A",
                            Marks = 82f,
                            StudentId = "S12345680"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = "MGT101",
                            GradeLetter = "B+",
                            Marks = 78f,
                            StudentId = "S12345681"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = "ACC101",
                            GradeLetter = "B",
                            Marks = 72f,
                            StudentId = "S12345681"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = "ECO101",
                            GradeLetter = "C+",
                            Marks = 68f,
                            StudentId = "S12345681"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = "BIO101",
                            GradeLetter = "A+",
                            Marks = 95f,
                            StudentId = "S12345682"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = "CHE101",
                            GradeLetter = "A",
                            Marks = 88f,
                            StudentId = "S12345682"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = "MATH101",
                            GradeLetter = "A",
                            Marks = 82f,
                            StudentId = "S12345682"
                        },
                        new
                        {
                            Id = 16,
                            CourseId = "CHE101",
                            GradeLetter = "A+",
                            Marks = 92f,
                            StudentId = "S12345683"
                        },
                        new
                        {
                            Id = 17,
                            CourseId = "PHY101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "S12345683"
                        },
                        new
                        {
                            Id = 18,
                            CourseId = "MATH101",
                            GradeLetter = "B+",
                            Marks = 78f,
                            StudentId = "S12345683"
                        },
                        new
                        {
                            Id = 19,
                            CourseId = "ECO101",
                            GradeLetter = "A",
                            Marks = 88f,
                            StudentId = "S12345684"
                        },
                        new
                        {
                            Id = 20,
                            CourseId = "MGT101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "S12345684"
                        },
                        new
                        {
                            Id = 21,
                            CourseId = "MATH101",
                            GradeLetter = "B",
                            Marks = 75f,
                            StudentId = "S12345684"
                        },
                        new
                        {
                            Id = 22,
                            CourseId = "ECO101",
                            GradeLetter = "A+",
                            Marks = 92f,
                            StudentId = "S12345685"
                        },
                        new
                        {
                            Id = 23,
                            CourseId = "FIN101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "S12345685"
                        },
                        new
                        {
                            Id = 24,
                            CourseId = "MATH101",
                            GradeLetter = "B+",
                            Marks = 78f,
                            StudentId = "S12345685"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
