// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USPEducation.Data;

#nullable disable

namespace USPGradeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322082304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("USPGradeSystem.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeLetter")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<float>("Marks")
                        .HasColumnType("real");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = "CS101",
                            GradeLetter = "A",
                            Marks = 85f,
                            StudentId = "1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = "CS102",
                            GradeLetter = "A+",
                            Marks = 92f,
                            StudentId = "1"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = "MATH101",
                            GradeLetter = "B+",
                            Marks = 78f,
                            StudentId = "1"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = "CS101",
                            GradeLetter = "C",
                            Marks = 65f,
                            StudentId = "2"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = "CS102",
                            GradeLetter = "F",
                            Marks = 45f,
                            StudentId = "2"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = "MATH101",
                            GradeLetter = "A",
                            Marks = 88f,
                            StudentId = "2"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = "CS101",
                            GradeLetter = "A+",
                            Marks = 95f,
                            StudentId = "3"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = "CS102",
                            GradeLetter = "A",
                            Marks = 82f,
                            StudentId = "3"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = "MATH101",
                            GradeLetter = "B",
                            Marks = 75f,
                            StudentId = "3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
